### ISSUE TITLE
Multiple Sheet Not Read 

### ISSUE THREAD

**Issue by anish-sherasiya** [vakata/spreadsheet#1]
Hello,

[vakata/](https://packagist.org/packages/vakata/)spreadsheet 
I want to read data from multiple sheets in an excel file

**Comment by vakata** [comment]
Both XLSX and XLS readers can be constructed with a parameter named $desiredSheet which defaults to the first sheet.

**Comment by anish-sherasiya** [comment]
how can i pass parameter can you provide me example ?
